sprint_1
Fedorova199/black-cat pull request #1
Opened 2022-01-06 16:40 UTC by Fedorova199

increment 3

2022-01-08 11:49 UTC, Bazys requested changes
привести структуру каталогов в соответствии с https://github.com/golang-standards/project-layout/blob/master/README_ru.md
дописать побольше тестов - добавлять и полчать не 1 а два или три урл для сокращения

2022-01-08 11:49 UTC, Bazys commented on cmd/shortener/handlers/handler.go
> +package handlers
этот файл должен распологаться в каталоге internal

2022-01-08 11:49 UTC, Bazys commented on cmd/shortener/handlers/handler.go
> +	u.urlmap = map[string]string{}
при каждом вызове функции создается новая, пустая мапка?
и при каждом вызове мы всегда новое значение записваем с ключом = 1.

2022-01-09 08:51 UTC, Fedorova199 commented
renewal

2022-01-10 16:48 UTC, merged